### ISSUE TITLE
change backgroud

### ISSUE THREAD

**Issue by rpoleij** [Nihvel/your_name#10]
if i want to change te background picture. i delete the yourname.jpg in the www/backgrounds folder and i put a new file with the new background picture and give the name yourname.jpg. but the background is still not changing

**Comment by Nihvel** [comment]
Hi, those steps are correct but you also have to restart HA. Probably, also clear the cache of your browser.

Another way is to modify the theme itself at this row `lovelace-background: 'center / cover no-repeat url("/local/backgrounds/yourname.jpg") fixed'` and replace 'yourname.jpg' with your wallpaper. This is a bit more invasive, and you still have to restart HA.

**Comment by rpoleij** [comment]
Thank you. I changed the name and now its working.Met vriendelijke groet,Ruud Poleij
-------- Oorspronkelijk bericht --------Van: Juri Calleri ***@***.***> Datum: 14-04-2021  13:32  (GMT+01:00) Aan: Nihvel/your_name ***@***.***> Cc: rpoleij ***@***.***>, Author ***@***.***> Onderwerp: Re: [Nihvel/your_name] change backgroud (#10) 
Hi, those steps are correct but you also have to restart HA. Probably, also clear the cache of your browser.
Another way is to modify the theme itself at this row lovelace-background: 'center / cover no-repeat url("/local/backgrounds/yourname.jpg") fixed' and replace 'yourname.jpg' with your wallpaper. This is a bit more invasive, and you still have to restart HA.
