### ISSUE TITLE
Transparent div

### ISSUE THREAD

**Issue by biofects** [Nihvel/your_name#13]
Im going to see if I can use the card-mod in your theme to not have popup transparent. I found this article that might be able to help
https://community.home-assistant.io/t/change-transparency-of-popups/226207

**Comment by biofects** [comment]
Ok so now the cards in Lovelace are not transparent, just the configuration cards this might work 👍

**Comment by biofects** [comment]
OK,  I have found the fix!! Add the following to top of the theme.

```
dialog-backdrop-filter: blur(20px) 
iron-overlay-backdrop-opacity: 1
iron-overlay-backdrop-background-color: rgba(0, 0, 0, 0.32))
```

I created a pull a merge request and submit if you would like.

**Comment by Nihvel** [comment]
Merged in https://github.com/Nihvel/your_name/pull/14 - Thanks a lot for your work!

**Comment by Nihvel** [comment]
closing
