### ISSUE TITLE
Unknown error when down this project

### ISSUE THREAD

**Issue by Mugrose** [Nihvel/your_name#15]
![Snipaste_2024-03-18_00-04-25](https://github.com/Nihvel/your_name/assets/144462940/150d6fec-8d47-48c9-a857-fea651c9dc8a)

Except unknown error, I can not see anything in the detailed window... but in 1.33 is ok.

**Comment by Nihvel** [comment]
Hi, I can't replicate the error above. I believe there might be issues with your connection or with your HA installation. I am able to (re)download it just fine.
