### ISSUE TITLE
Still some issues with background colors :-)

### ISSUE THREAD

**Issue by fribse** [Nihvel/your_name#2]
Hi Nihvel
Thankyou for the very fast response to the previously posted issue.
There are still some challenges.
I have updated the theme, and I've cleared the cache, not sure if  it is somehow cached further?
This is a hacs example:
First if I highlight the text:
![image](https://user-images.githubusercontent.com/13660621/84704519-405d5f80-af5a-11ea-8ce1-2d67f3890c4c.png)
And then without the highlighting:
![image](https://user-images.githubusercontent.com/13660621/84704538-4a7f5e00-af5a-11ea-8c07-02f5e95bd424.png)
Then the add-one page (documentation), with highlighted text:
![image](https://user-images.githubusercontent.com/13660621/84704975-f4f78100-af5a-11ea-9939-1ddb8c2d4256.png)
and without:
![image](https://user-images.githubusercontent.com/13660621/84704985-fb85f880-af5a-11ea-8246-c84f26517c42.png)

**Comment by Nihvel** [comment]
Have you restarted Home Assistant after the update?
![screenshot-yourname](https://user-images.githubusercontent.com/24250443/84779460-b73f3a80-afe4-11ea-8629-faf0cca3c7ed.png)

**Comment by fribse** [comment]
Yes, it's really weird, I've restarted HA, I've cleared the cache in Firefox (oh could it be firefox specific??)

**Comment by fribse** [comment]
Oh, that's odd, after clearing the cache again, and shutting down FF, and restarting it, it shows it correctly, wtf???
So I'll close this, thankyou for the great work on this, I really like the design!
