### ISSUE TITLE
0.113 makes the template loose the 'edges'

### ISSUE THREAD

**Issue by fribse** [Nihvel/your_name#3]
Or at least they get very faint, can't really put my finger on it, but it looks odd...
![image](https://user-images.githubusercontent.com/13660621/88449790-185ef700-ce4a-11ea-9893-3bdd597f2cca.png)

**Comment by Nihvel** [comment]
I'm working on this to fix, I haven't updated to 0.113 yet and wasn't much online lately.

**Comment by Nihvel** [comment]
HACS should already show the new version. Apply the update and restart Home Assistant for the updated version to take effect. Please, let me know if it worked

I thank the user @moosedookie for the fix

**Comment by fribse** [comment]
Works perfectly. Thankyou
