### ISSUE TITLE
Toggle switch hard to see

### ISSUE THREAD

**Issue by axwell** [Nihvel/your_name#5]
hello,
toggle switches are hard to see when off and background is black and screen is dim, for example the attached picture.

Is it possible to make it a bit more visible ?
![Overview-Home-Assistant](https://user-images.githubusercontent.com/7890878/90784777-4a109400-e30a-11ea-98ac-65f6722dff5a.png)

**Comment by Nihvel** [comment]
I have a list of changes I wanted to apply to this theme and I finally managed to find some time for it. Expect an update in some minutes and let me know if the issue is fixed ;)

**Comment by lubitcasa** [comment]
acabo de actualizar a la ultima version y tuve que volver atras....se pierde la transparencias de las cards y desaparece la foto de fondo

**Comment by axwell** [comment]
Perfect, works great !
