### ISSUE TITLE
Is there a problem with --label-badge-red?

### ISSUE THREAD

**Issue by fribse** [Nihvel/your_name#8]
It seems like the 'red' color is just blue in the template?

I've tried setting up both a custom battery card and a custom dual gauge card, and they are just shown as blue when I beleive the should be red?

**Comment by Nihvel** [comment]
Hi, yes, you're right that the red badge is actually blue. It is not an error. When you set the red color to the red badge, it will (somehow) overwrites and takes priority on the blue badge. Let's say that to set the red badge to the blue color bypasses this behavior making this theme look more blue-ish.

I've seen the same hack on other themes as well.

Also, this theme is not updated to reflect the latest home assistant UI changes. The transparency set on the HA cards have a bad impact on the home assistant UI too, same for the button-card.
While, in my dev own branch, I solved the issue with the custom plugin 'button-cards', the UI of Home Assistant still looks imperfect and I haven't found a solution yet to keep using transparency on Lovelace without affecting other HA pages.

**Comment by fribse** [comment]
Ok, gotcha, thankyou for the feedback! I'm not sure how to do the override you mention? Could you point me to an example?

**Comment by Nihvel** [comment]
> Ok, gotcha, thankyou for the feedback! I'm not sure how to do the override you mention? Could you point me to an example?

The override i mention is that one where people set their own preferred color on the red_badge. I did that in this theme and set it to color blue ;)

**Comment by fribse** [comment]
Got it, thanks!
